name: 'Setup Node and Install Dependencies'
description: 'Checks out code, sets up Node.js from package.json, and installs dependencies with npm ci'

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash